%% experiment VI: classical conditioning - "trial-less"
% description goes here

%% initialization
Jeong2022_preface;

%% used fixed random seed
rng(0);

%% key assumptions
use_clicks = 0;
use_cs_offset = 0;

%% analysis parameters
isi_cutoff = .5;
baseline_period = [-.5,0];
cs_period = [0,.5];
us_period = [0,.5];

%% experiment parameters
cs_dur = .25;
trace_dur = 3;
icsi_mu = 33;
icsi_min = .25;
icsi_max = 99;

%% simulation parameters
n_rewards = 500;

%% inter-CS-intervals
icsi_pd = truncate(makedist('exponential','mu',icsi_mu),icsi_min,icsi_max);
icsi = random(icsi_pd,n_rewards,1);
icsi = dt * round(icsi / dt);
n_bins = round(max(icsi) / icsi_mu) * 10;
icsi_edges = linspace(icsi_min,icsi_max,n_bins);
icsi_counts = histcounts(icsi,icsi_edges);
icsi_counts = icsi_counts ./ nansum(icsi_counts);
icsi_pdf = pdf(icsi_pd,icsi_edges);
icsi_pdf = icsi_pdf ./ nansum(icsi_pdf);

%% simulation time
dur = sum(icsi) + icsi_max;
time = 0 : dt : dur - dt;
n_states = numel(time);
state_edges = linspace(0,dur,n_states+1);

%% CS onset times
cs_onset_times = cumsum(icsi);
cs_onset_times = dt * round(cs_onset_times / dt);
cs_onset_counts = histcounts(cs_onset_times,state_edges);

%% CS offset times
cs_offset_times = cs_onset_times + cs_dur;
cs_offset_times = dt * round(cs_offset_times / dt);
cs_offset_counts = histcounts(cs_offset_times,state_edges);

%% click times
click_times = cs_offset_times + trace_dur;
click_times = dt * round(click_times / dt);
click_counts = histcounts(click_times,state_edges);
n_clicks = sum(click_counts);

%% CS flags
cs_ison = sum(...
    time >= cs_onset_times & ...
    time <= cs_offset_times,1)';

%% reaction times
reaction_times = repmat(.5,n_rewards,1);
% reaction_times = linspace(1,.1,n_rewards)';
reaction_times = max(reaction_times,dt*2);
if ~use_clicks
    reaction_times = 0;
end

%% reward times
reward_times = click_times + reaction_times;
reward_times = dt * round(reward_times / dt);
reward_counts = histcounts(reward_times,state_edges);

%% CS(i)-US(i-1)-intervals
csusi = abs(cs_onset_times - [-inf;reward_times(1:end-1)]);
csusi_edges = 0 : isi_cutoff : isi_cutoff * n_bins;
csusi_counts = histcounts(csusi,csusi_edges);

%% flag previous & intermediate CS/reward pairs
cs_intermediate_flags = icsi < (reward_times - cs_onset_times);
cs = categorical(cs_intermediate_flags,[0,1],{'CS_{prev.}','CS_{interm.}'});
cs_set = categories(cs);
% bah = abs(cs_onset_times - [-inf;reward_times(1:end-1)]);
% a = [icsi,cs_onset_times,reward_times,csusi,bah];
% a(1:25,:)

%% microstimuli
stimulus_trace = stimulustracefun(y0,tau,time)';
mus = linspace(1,0,n);
microstimuli = microstimulusfun(stimulus_trace,mus,sigma);

%% UNCOMMENT TO REPLACE MICROSTIMULI WITH COMPLETE SERIAL COMPOUND
% csc = zeros(n_states,n);
% pulse_duration = .5;
% pulse_length = floor(pulse_duration / dt);
% for ii = 1 : n
%     idcs = (1 : pulse_length) + (ii - 1) * pulse_length;
%     csc(idcs,ii) = 1;
% end
% microstimuli = csc;
% microstimuli = microstimuli / max(sum(microstimuli,2));

%% concatenate all stimulus times
stimulus_times = {...
    reward_times,...
    cs_onset_times};
if use_clicks
    stimulus_times = [...
        stimulus_times,...
        click_times];
end
if use_cs_offset
    stimulus_times = [...
        stimulus_times,...
        cs_offset_times];
end

%% concatenate all state flags
cs_flags = [...
    cs_ison];

%% TD learning
[state,value,rpe,exp2_weights] = tdlambda(...
    time,[],stimulus_times,reward_times,microstimuli,[],...
    'alpha',alpha,...
    'gamma',gamma,...
    'lambda',lambda);

%% compute 'DA signal'
padded_rpe = padarray(rpe,dlight_kernel.nbins/2,0);
da = conv(padded_rpe(1:end-1),dlight_kernel.pdf,'valid');
da = da / max(dlight_kernel.pdf);

%% get reward-aligned snippets of DA signal
[da_cs_snippets,da_cs_time] = ...
    signal2eventsnippets(time,da,cs_onset_times,cs_period,dt);
[da_us_snippets,da_us_time] = ...
    signal2eventsnippets(time,da,reward_times,us_period,dt);
[da_baseline_snippets,da_baseline_time] = ...
    signal2eventsnippets(time,da,reward_times,baseline_period,dt);

%% ISI-based reward selection
valid_flags = ...
    icsi >= isi_cutoff & ...
    csusi >= isi_cutoff;
da_reward_snippets(~valid_flags,:) = nan;
da_baseline_snippets(~valid_flags,:) = nan;

%% compute 'DA response' metric

% preallocation
da_cs_response = nan(n_rewards,1);
da_us_response = nan(n_rewards,1);

% iterate through rewards
for ii = 1 : n_rewards
    da_cs_response(ii) = ...
        sum(da_cs_snippets(ii,:)) - sum(da_baseline_snippets(ii,:));
    da_us_response(ii) = ...
        sum(da_us_snippets(ii,:)) - sum(da_baseline_snippets(ii,:));
end

%% figure 6: experiment VI

% figure initialization
figure(figopt,...
    'name','experiment VI: test 8');

% axes initialization
n_rows = 4;
n_cols = 6;
sp_stimulus = subplot(n_rows,n_cols,(1:n_cols/2)+n_cols*0);
sp_state = subplot(n_rows,n_cols,(1:n_cols/2)+n_cols*1);
sp_rpe = subplot(n_rows,n_cols,(1:n_cols/2)+n_cols*2);
sp_value = subplot(n_rows,n_cols,(1:n_cols/2)+n_cols*3);
sp_icsi = subplot(n_rows,n_cols,n_cols*0+n_cols/2+1);
sp_csusi = subplot(n_rows,n_cols,n_cols*0+n_cols/2+2);
sp_cstype = subplot(n_rows,n_cols,n_cols*0+n_cols/2+3);
sp_reaction = subplot(n_rows,n_cols,n_cols*1+n_cols/2+1);
sp_dunnoyet2 = subplot(n_rows,n_cols,n_cols*1+n_cols/2+2);
sp_dunnoyet3 = subplot(n_rows,n_cols,n_cols*1+n_cols/2+3);
sp_bslresponse = subplot(n_rows,n_cols,n_cols*2+n_cols/2+1);
sp_csresponse = subplot(n_rows,n_cols,n_cols*2+n_cols/2+2);
sp_usresponse = subplot(n_rows,n_cols,n_cols*2+n_cols/2+3);
sp_test8_csratio = subplot(n_rows,n_cols,n_cols*3+n_cols/2+1);
sp_test8_usratio = subplot(n_rows,n_cols,n_cols*3+n_cols/2+2);
sp_test8_bslcorrcsratio = subplot(n_rows,n_cols,n_cols*3+n_cols/2+3);

% concatenate axes
sps = [...
    sp_stimulus;...
    sp_state;...
    sp_rpe;...
    sp_value;...
    sp_icsi;...
    sp_csusi;...
    sp_reaction;...
    sp_cstype;...
    sp_bslresponse;...
    sp_csresponse;...
    sp_usresponse;...
    sp_test8_csratio;...
    sp_test8_usratio;...
    sp_test8_bslcorrcsratio;...
    ];

% axes settings
arrayfun(@(ax)set(ax.XAxis,'exponent',0),sps);
set(sps,axesopt);
set(sp_stimulus,...
    'ycolor','none');
set(sp_icsi,...
    'xlim',[0,100]);
set(sp_csusi,...
    'xlim',[0,csusi_edges(end)]);
set(sp_cstype,...
    'xlim',[0,1]+[-1,1],...
    'xtick',[0,1],...
    'xticklabel',cs_set);
set(sp_bslresponse,...
    'xlim',baseline_period);
set(sp_csresponse,...
    'xlim',cs_period);
set(sp_usresponse,...
    'xlim',us_period);

% axes titles
title(sp_bslresponse,'Baseline period');
title(sp_csresponse,'CS period');
title(sp_usresponse,'Reward period');
title(sp_test8_csratio,'Test VIII');
title(sp_test8_usratio,'Test VIII');
title(sp_test8_bslcorrcsratio,'Test VIII');

% axes labels
xlabel(sp_stimulus,'Time (s)');
xlabel(sp_state,'Time (s)');
ylabel(sp_state,'State feature #');
xlabel(sp_rpe,'Time (s)');
ylabel(sp_rpe,'RPE (a.u.)');
xlabel(sp_value,'Time (s)');
ylabel(sp_value,'Value (a.u.)');
xlabel(sp_icsi,'Inter-CS interval (s)');
ylabel(sp_icsi,'PDF');
xlabel(sp_csusi,'CS_{interm.}-US_{prev.} interval (s)');
ylabel(sp_csusi,'Count');
xlabel(sp_reaction,'Time (s)');
ylabel(sp_reaction,'Reaction time (s)');
ylabel(sp_cstype,'Count');
xlabel(sp_bslresponse,'Time since CS_{prev.} (s)');
ylabel(sp_bslresponse,'DA (a.u.)');
xlabel(sp_csresponse,'Time since CS (s)');
ylabel(sp_csresponse,'DA (a.u.)');
xlabel(sp_usresponse,'Time since US (s)');
ylabel(sp_usresponse,'DA (a.u.)');
ylabel(sp_test8_csratio,...
    {'Ratio of CS response','(interm. / prev.)'});
ylabel(sp_test8_usratio,...
    {'Ratio of US response','(interm. / prev.)'});
ylabel(sp_test8_bslcorrcsratio,...
    {'Ratio of baseline-corrected','CS response (interm. / prev.)'});

% time selection
last_intermediate_idx = find(cs_intermediate_flags & valid_flags,1,'last');
dur2plot = 60;
time_flags = ...
    time >= cs_onset_times(last_intermediate_idx) - dur2plot / 2 & ...
    time < cs_onset_times(last_intermediate_idx) + dur2plot / 2;
idcs = find(time_flags);
time_win = [time(idcs(1)),time(idcs(end))];

% plot stimulus trace
if use_clicks
    stem(sp_stimulus,...
        time(idcs),click_counts(idcs),...
        'color','k',...
        'marker','none');
end
stem(sp_stimulus,...
    cs_onset_times(~cs_intermediate_flags),ones(sum(~cs_intermediate_flags),1),...
    'color',cs_previous_clr,...
    'marker','none',...
    'linewidth',1);
stem(sp_stimulus,...
    cs_onset_times(cs_intermediate_flags),ones(sum(cs_intermediate_flags),1),...
    'color',cs_intermediate_clr,...
    'marker','none',...
    'linewidth',1);
stem(sp_stimulus,...
    reward_times(~cs_intermediate_flags),ones(sum(~cs_intermediate_flags),1),...
    'color',cs_previous_clr,...
    'marker','.',...
    'markersize',20,...
    'linewidth',1);
stem(sp_stimulus,...
    reward_times(cs_intermediate_flags),ones(sum(cs_intermediate_flags),1),...
    'color',cs_intermediate_clr,...
    'marker','.',...
    'markersize',20,...
    'linewidth',1);

% plot state features
imagesc(sp_state,time(idcs)+dt/2,[],state(idcs,:)');

% plot RPE
stem(sp_rpe,time(idcs),rpe(idcs),...
    'color','k',...
    'marker','none');

% plot DA signal
plot(sp_rpe,time(idcs),da(idcs),...
    'color',highlight_clr);

% plot value trace
stairs(sp_value,time(idcs),value(idcs),...
    'color','k');

% update axis limits
set([sp_stimulus,sp_state,sp_rpe,sp_value],...
    'xlim',time_win);

% legend
if use_clicks
    leg_str = [cs_set;{'click';'reward'}];
else
    leg_str = [cs_set;strrep(cs_set,'CS','US')];
end
legend(sp_stimulus(1),leg_str,...
    'location','best',...
    'box','off');

% plot inter-CS-interval distribution
stem(sp_icsi,icsi_mu,max([icsi_counts,icsi_pdf]),...
    'color','k',...
    'marker','v',...
    'markersize',10,...
    'markerfacecolor','k',...
    'markeredgecolor','none',...
    'linewidth',2);
histogram(sp_icsi,...
    'binedges',icsi_edges,...
    'bincounts',icsi_counts .* (icsi_edges(1:end-1)>=isi_cutoff),...
    'facecolor','w',...
    'edgecolor','k',...
    'facealpha',1,...
    'linewidth',1);
histogram(sp_icsi,...
    'binedges',icsi_edges,...
    'bincounts',icsi_counts .* (icsi_edges(1:end-1)<isi_cutoff),...
    'facecolor',[1,1,1] *.75,...
    'edgecolor','k',...
    'facealpha',1,...
    'linewidth',1);
plot(sp_icsi,icsi_edges,icsi_pdf,...
    'color','k',...
    'linewidth',2);

% plot CS(i)-US(i-1)-interval distribution
histogram(sp_csusi,...
    'binedges',csusi_edges,...
    'bincounts',csusi_counts .* (csusi_edges(1:end-1)>=isi_cutoff),...
    'facecolor','w',...
    'edgecolor','k',...
    'facealpha',1,...
    'linewidth',1);
histogram(sp_csusi,...
    'binedges',csusi_edges,...
    'bincounts',csusi_counts .* (csusi_edges(1:end-1)<isi_cutoff),...
    'facecolor',[1,1,1] *.75,...
    'edgecolor','k',...
    'facealpha',1,...
    'linewidth',1);

% plot reaction times
if use_clicks
    plot(sp_reaction,...
        reward_times,reaction_times,...
        'color','k',...
        'marker','.',...
        'markersize',5,...
        'linestyle','none');
end

% plot CS distribution
patch(sp_cstype,...
    0+[-1,1,1,-1]*1/4,[0,0,1,1]*sum(~cs_intermediate_flags),...
    cs_previous_clr,...
    'edgecolor',cs_previous_clr,...
    'linewidth',1.5,...
    'facealpha',2/3);
patch(sp_cstype,...
    1+[-1,1,1,-1]*1/4,[0,0,1,1]*sum(cs_intermediate_flags),...
    cs_intermediate_clr,...
    'edgecolor',cs_intermediate_clr,...
    'linewidth',1.5,...
    'facealpha',2/3);

% plot average CS-aligned baseline signal
plot(sp_bslresponse,baseline_period,[0,0],':k');
da_baseline_mu = nanmean(da_baseline_snippets(~cs_intermediate_flags,:));
plot(sp_bslresponse,...
    da_baseline_time,da_baseline_mu,...
    'color',cs_previous_clr,...
    'linewidth',1.5);
da_baseline_mu = nanmean(da_baseline_snippets(cs_intermediate_flags,:));
plot(sp_bslresponse,...
    da_baseline_time,da_baseline_mu,...
    'color',cs_intermediate_clr,...
    'linewidth',1.5);

% plot average CS-aligned reward signal
plot(sp_csresponse,cs_period,[0,0],':k');
da_cs_mu = nanmean(da_cs_snippets(~cs_intermediate_flags,:));
plot(sp_csresponse,...
    da_cs_time,da_cs_mu,...
    'color',cs_previous_clr,...
    'linewidth',1.5);
da_cs_mu = nanmean(da_cs_snippets(cs_intermediate_flags,:));
plot(sp_csresponse,...
    da_cs_time,da_cs_mu,...
    'color',cs_intermediate_clr,...
    'linewidth',1.5);

% plot average reward-aligned reward signal
plot(sp_usresponse,us_period,[0,0],':k');
da_us_mu = nanmean(da_us_snippets(~cs_intermediate_flags,:));
plot(sp_usresponse,...
    da_us_time,da_us_mu,...
    'color',cs_previous_clr,...
    'linewidth',1.5);
da_us_mu = nanmean(da_us_snippets(cs_intermediate_flags,:));
plot(sp_usresponse,...
    da_us_time,da_us_mu,...
    'color',cs_intermediate_clr,...
    'linewidth',1.5);

% test 8: Ratio of CS responses (intermediate / previous)
scatter(sp_usresponse,xx,da_us_response,20,...
    colorlerp([early_clr; late_clr],n_rewards),...
    'marker','o',...
    'markerfacealpha',.5,...
    'markerfacecolor','flat',...
    'markeredgecolor','flat',...
    'linewidth',1);
plot(sp_usresponse,xx,mdl.predict(xx),...
    'color',highlight_clr,...
    'linestyle',repmat('-',1,1+(mdl.Coefficients.pValue(end)>.05)),...
    'linewidth',1.5);
plot(sp_usresponse,xlim(sp_usresponse),[1,1]*0,':k');
text(sp_usresponse,.95,.95,sprintf('r = %.2f',rho),...
    'horizontalalignment','right',...
    'units','normalized',...
    'color','k');
text(sp_usresponse,.95,.85,sprintf('p = %.2f',pval),...
    'horizontalalignment','right',...
    'units','normalized',...
    'color','k');

% test 2: DA responses as a function of previous IRI
% nan_flags = isnan(da_response);
% [rho,pval] = corr(iri(~nan_flags),da_response(~nan_flags));
% mdl = fitlm(iri,da_response);
% scatter(sp_test2,iri,da_response,20,...
%     colorlerp([early_clr; late_clr],n_rewards),...
%     'marker','o',...
%     'markerfacealpha',.5,...
%     'markerfacecolor','flat',...
%     'markeredgecolor','flat',...
%     'linewidth',1);
% plot(sp_test2,mdl.Variables.x1,mdl.predict(mdl.Variables.x1),...
%     'color',highlight_clr,...
%     'linestyle',repmat('-',1,1+(mdl.Coefficients.pValue(end)>.05)),...
%     'linewidth',1.5);
% plot(sp_test2,xlim(sp_test2),[1,1]*0,':k');
% text(sp_test2,.95,.95,sprintf('r = %.2f',rho),...
%     'horizontalalignment','right',...
%     'units','normalized',...
%     'color','k');
% text(sp_test2,.95,.85,sprintf('p = %.2f',pval),...
%     'horizontalalignment','right',...
%     'units','normalized',...
%     'color','k');

% axes linkage
arrayfun(@(ax1,ax2,ax3,ax4)linkaxes([ax1,ax2,ax3,ax4],'x'),...
    sp_stimulus,sp_state,sp_rpe,sp_value);
linkaxes(sp_rpe,'y');
linkaxes(sp_value,'y');
linkaxes([sp_bslresponse,sp_csresponse,sp_usresponse],'y');

% annotate model parameters
annotateModelParameters;
