m = 1e3;
ti = 0;
tf = 14;
x = linspace(ti,tf,m);
y1 = zeros(m,1);
[~,idx] = min(abs(x-2));
y1(idx) = 1;
y2 = zeros(m,1);
[~,idx] = min(abs(x-8));
y2(idx) = 1;

figure; stem(x,y1);

kernels = eye(m);
for kk = 2 : m
    kernels(:,kk) = normpdf(x,x(kk),.15*x(kk));
end
kernels = kernels / nansum(kernels(:,2));

s1 = kernels' * y1;
s2 = kernels' * y2;
figure('color','w');
set(gca,...
    'box','off',...
    'tickdir','out',...
    'nextplot','add',...
    'layer','top',...
    'ticklength',[1,1]*.025,...
    'ytick',[],...
    'xcolor','k',...
    'ycolor','k',...
    'fontsize',12,...
    'linewidth',2,...
    'plotboxaspectratio',[2,1,1]);
xlabel('"Internal" time (s)');
ylabel('PDF');
plot(x,s1,x,s2,...
    'linewidth',1.5);
leg=legend({'2-s CS','8-s CS'},...
    'autoupdate','off');