dt_str = sprintf('dt = %.4g [s]',dt);
eta_str = sprintf('\\eta = %.4g [s]',eta);
gamma_str = sprintf('\\gamma = %.4g',gamma);
alpha_str = sprintf('\\alpha = %.4g',alpha);
lambda_str = sprintf('\\lambda = %.4g',lambda);
tau_str = sprintf('\\tau = %.4g',tau);
sigma_str = sprintf('\\sigma = %.4g',sigma);
n_str = sprintf('n = %i',n);
psi_str = sprintf('\\psi = %.4g',psi);
param_str = strjoin({'Parameters:',...
    dt_str,eta_str,gamma_str,alpha_str,...
    lambda_str,tau_str,sigma_str,n_str,psi_str},'\n');
annotation('textbox',[.025,.5,.1,.1],...
    'string',param_str,...
    'fitboxtotext','on',...
    'horizontalalignment','left',...
    'verticalalignment','middle',...
    'fontsize',12,...
    'edgecolor','k',...
    'linewidth',2);
drawnow;