%% dLight kernel definition
dlight_kernel = gammakernel(...
    'peakx',.2,...
    'binwidth',dt);

%% reward rate kernel settings
% rwdrate_kernel = hypkernel(...
%     'med',180,...
%     'binwidth',dt);
rwdrate_kernel = expkernel(...
    'mu',60*5,...
    'binwidth',dt);